src/models/UserEditForm.py
from typing import Optional
from flask_wtf import FlaskForm

from wtforms import StringField, SubmitField, PasswordField, FileField, IntegerField, SelectField
from wtforms.validators import EqualTo, DataRequired, Length

class UserEditForm(FlaskForm):
    ime = StringField('Name: ', validators=[DataRequired()])
    prezime = StringField('Surname: ', validators=[DataRequired()])
    korisnickoIme = StringField('Username: ', validators=[DataRequired()])
    uloga = SelectField('Role:', choices=[(0, '112 Dispatcher'), (1, 'Doctor'), (2, 'Firefighter'), (3, 'Policeman'), (4, 'Administrator')])  # Ovaj postavi kada se bude radio route,
    brojMob = StringField('Phone number: ', validators=[DataRequired('Wrong number')])
    email = StringField('Email: ', validators=[DataRequired()])
    fotografija = FileField('Your photo: ')
    stanica = SelectField('Stanica: ', coerce=int)  # TODO kako ako se uređuje dispatcher, on nema stanicu
    lozinka = PasswordField('Password: ', validators=[])
    lozinkaProvjera = PasswordField('Repeat password:',
                                  validators=[EqualTo('lozinka', message='Passwords must match')])
    submit = SubmitField('Save changes')

src/views/act_request.py
from flask import render_template, request, redirect, Blueprint, session, url_for, flash
from models.DBModels import Akcija, Spasioci, Zahtjev, Korisnik
from shared import db

act_request = Blueprint('act_request', __name__)

class DataDisplay:
    def __init__(self, idZahtjeva, idAkcija, hitnost, idSpasioc, naziv, opis, datum):
        self.idZahtjeva = idZahtjeva
        self.idAkcija= idAkcija
        self.hitnost = hitnost
        self.idSpasioc= idSpasioc
        self.naziv = naziv
        self.opis = opis
        self.datum = datum


@act_request.route('/act_requests', methods=['GET'])
def show_requests():
    # Preusmjeravanje za nedozvoljene uloge
    if session.get("username") == None:
        return redirect(url_for('auth.login'))
    if session.get("role") not in ["Doctor", "Firefighter", "Policeman"]:
        return redirect(url_for('views.home_page'))

    username = session.get("username")

    id = Korisnik.query.filter_by(korisnickoIme=username).first().id
    spasioc = Spasioci.query.filter_by(idSpasioc=id).first()

    if spasioc.idAkcije:
        # Ako je dio akcije ispiši odgovarajuću poruku
        return render_template('Act_Requests.html.j2', dio_akcije=True)

    requests = Zahtjev.query.filter_by(spasioc=int(id)).all()

    data_display = []

    for request in requests:
        #dodaj nazive akcija i opise u skup podataka
        action = Akcija.query.filter_by(id=request.idAkcija).first()
        date = action.datum.strftime("%Y-%m-%d %H:%M:%S")
        action_opis_cut = action.opis[0:50] + "..."
        data = DataDisplay(request.id, request.idAkcija, request.hitnost, request.spasioc, action.naziv, action_opis_cut, date)
        data_display.append(data)

    return render_template('Act_Requests.html.j2', data_display=data_display)


@act_request.route('/act_request/accept', methods=['POST'])
def accept_request():
    spasioc_username = session.get('username')
    idSpasioc = Korisnik.query.filter_by(korisnickoIme=spasioc_username).first().id
    spasioc = Spasioci.query.filter_by(idSpasioc=idSpasioc).first()

    idAkcija = int(request.form['accept'])
    idZahtjev = int(request.form['id_zahtjev'])

    # Provjera da li akcija postoji i da li je aktivna --- Ako u međuvremenu akcija završila, javlja se poruka o završetku akcije
    #                                                       inače se vraća na Home page i spasioc se povezuje sa akcijom
    if Akcija.query.filter_by(id=idAkcija).first() and not Akcija.query.filter_by(id=idAkcija).first().gotova:
        if 'accept' in request.form.keys():
            spasioc.idAkcije = idAkcija
            spasioc.dostupnost = False
            Zahtjev.query.filter_by(id=idZahtjev).delete()
            db.session.commit()
    else:
        flash(message="Akcija je u međuvremenu završila!", category="error")
        return redirect(url_for('act_request.show_requests'))

    return redirect(url_for('views.home_page'))

src/views/applications.py
from random import random

from flask import render_template, request, redirect, Blueprint, session, url_for
from models.DBModels import Korisnik, Spasioci
from shared import db

applications = Blueprint('applications', __name__)


@applications.route('/applications', methods=['GET', 'POST'])
def view_applications():
    print(session.get("role"))
    if session.get("role") != "Administrator":
        return redirect(url_for('views.home_page'))
    users = Korisnik.query.filter_by(obraden=False)
    return render_template('UserApplications.html.j2', users=users, session=session)


@applications.route('/handle_application', methods=['POST'])
def handle_application():
    if session.get("role") != "Administrator":
        return redirect(url_for('views.home_page'))
    if 'accept' in request.form.keys():
        korisnickoIme = request.form['accept']
        user = Korisnik.query.filter_by(korisnickoIme=korisnickoIme).first()
        user.obraden = True
        if user.uloga not in ['112 Dispatcher', 'Administrator']:
            spasioc = Spasioci(idSpasioc=user.id, sifStanice=None, dostupnost=True, latitude=round(random()+45, 4), longitude=round(random()+15, 4))
            db.session.add(spasioc)
        db.session.commit()
    else:
        korisnickoIme = request.form['reject']
        Korisnik.query.filter_by(korisnickoIme=korisnickoIme).delete()
    db.session.commit()
    return redirect('/applications')

src/views/auth.py
from flask import Blueprint, render_template, session, redirect, url_for, request

from models.LoginForm import LoginForm
from models.RegistrationForm import RegisterForm
from models.DBModels import Korisnik, Stanica
from shared import db
from werkzeug.utils import secure_filename
from shared import ALLOWED_EXTENSIONS,UPLOAD_FOLDER
import os
auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    error = None
    form = LoginForm()
    if request.method == 'POST':
        if Korisnik.query.filter_by(korisnickoIme=form.username.data, lozinka=form.password.data).first() is not None:
            data = Korisnik.query.filter_by(korisnickoIme=form.username.data, lozinka=form.password.data).first()
            if data.obraden:
                session["username"] = form.username.data
                session["role"] = data.uloga

                # dodatni parametar za voditelja stanice
                idStanice = db.session.query(Stanica).filter_by(idVoditelja=data.id).first()
                if idStanice:
                    print(idStanice.sifStanice)
                    session["idStanice"] = idStanice.sifStanice
                    
                return redirect(url_for('views.home_page'))
            else:
                error = "Your account hasn't been validated!"
        else:
            error = "Username or password invalid!"
    elif session.get("username") is not None:
        return redirect(url_for('views.home_page'))
    return render_template('LoginForm.html.j2', form=form, error=error, session=session)

@auth.route('/register', methods=['GET', 'POST'])  # Register route
def register():
    form = RegisterForm()
    if request.method == 'POST' and form.validate():  # If form was successful check if user already exists
        if Korisnik.query.filter_by(email=form.email.data).first() is not None:
            form.email.errors.append("Email already in use!")
        elif Korisnik.query.filter_by(korisnickoIme=form.username.data).first() is not None:
            form.username.errors.append('Username already in use!')
        else:
            entry = Korisnik(form.name.data, form.surname.data, form.email.data,
                             form.phoneNumber.data, form.username.data, form.picture.data.filename,
                             form.password.data, form.role.data, False)
            file = request.files['picture']
            if file and allowed_file(file.filename):
                filename = secure_filename(file.filename)
                file.save(os.path.join(UPLOAD_FOLDER, filename))
                db.session.add(entry)
                db.session.commit()
                return redirect(url_for('auth.login'))
            else:
                form.picture.errors.append('.png or .jpg files only!')
    elif session.get("username") is not None:
        return redirect(url_for('views.home_page'))

    return render_template('RegisterForm.html.j2', form=form, session=session)



@auth.route('/signout', methods=['GET'])
def signout():
    session.clear()
    return redirect(url_for('views.home_page'))


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

src/templates/Act_Requests.html.j2
{% extends "base.html" %}

{% block content %}
    {{ super() }}

    {% if dio_akcije %}
      <div class="cover-container d-flex h-100 p-3 mx-auto flex-column text-center">
        <main role="main" class="inner cover">
            <h3 class="cover-heading">Već ste dio jedne akcije</h1>
           
        </main>
      </div>
    
    {% elif not data_display %}
      <div class="cover-container d-flex h-100 p-3 mx-auto flex-column text-center">
        <main role="main" class="inner cover">
            <h3 class="cover-heading">Nema aktivnih zahtjeva</h1>
           
        </main>
      </div>

    {% else %}
      <table class="table">
          <thead>
              <tr>
              {% for col in ['ID Zahtjeva', 'Naziv Akcije', 'Hitnost', 'Opis Akcije', 'Datum'] %}
                  <th scope="col">{{col}}</th>
              {% endfor %}
              <th style="text-align:center" scope="col"> Prihvati zahtjev </th>
              </tr>
          </thead>
          <tbody>
              {% for data in data_display %}
                  <tr>
                      <td>{{data.idZahtjeva}}</td>
                      <td>{{data.naziv}}</td>
                      <td>{{data.hitnost}}</td>
                      <td>{{data.opis}}</td>
                      <td>{{data.datum}}</td>
                      <td style="text-align:center">
                          <form action="{{url_for('act_request.accept_request')}}" method="POST">
                          <button type="submit" class="btn btn-success" name="accept" value="{{data.idAkcija}}">Prihvati</button>
                          <input type="hidden" name="id_zahtjev" value="{{data.idZahtjeva}}">
                          </form>
                      </td>
                  </tr>
              {% endfor %}
          </tbody>
      </table>
    {% endif %}

    {% with messages = get_flashed_messages(with_categories=true)%}
    {% if messages %}
      {% for category, message in messages %}
      {% if category =="error" %}
        <div class="alert alert-danger alert-dismissable" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

{% endblock %}

src/templates/AddNewRescuerForm.html.j2
{% extends "base.html" %}

{% block content %}
{{ super() }}
<div class="d-flex justify-content-center">
    <div class="h-75 w-25" style="margin-top:25vh">
        <div class="pt-3 col-md-10 col-sm-8 col-xs-12 border rounded shadow">
            <h4>Add new rescuer</h4>
            <form method="POST" enctype = "multipart/form-data" class="m-3">
                {{ form.csrf_token }}
                <div class="row pt-3">
                    {% if error %}
                    {{ form.Rescuers.label()}}
                    {{ form.Rescuers(class="form-control selectpicker", disabled="True")}}
                        {% else %}
                        {{ form.Rescuers.label()}}
                        {{ form.Rescuers(class="form-control selectpicker")}}
                    {% endif %}
                </div>
                <div class="col-md-11 col-sm-4 col-xs-12 p-0 pt-4">
                    {% if error %}
                    {{ form.submit(class="btn btn-primary w-100 ml-2", disabled="True") }}
                    {% else %}
                    {{ form.submit(class="btn btn-primary w-100 ml-2")}}
                    {% endif %}
                </div>
                <div class="form-text text-center text-danger">
                    {% if error %}
                        {{ error }}
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

src/templates/HomePage.html.j2
{% extends "base.html" %}

{% block content %}

<div class="container">

    <div class="jumbotron" style="background-image: url(static/landing_bg.jpg); background-size: 100%; color: white; text-shadow: 2px 2px #00000062; padding-top: 7%; padding-bottom: 8%;">
    <h1 class="display-3">Halo112</h1>
    <p class="h4">Halo112 je aplikacija koja olakšava koordinaciju rada svih službi za pomoć.</p>
    <p class="pt-3">
        {% if not role %}
            <a class="btn btn-lg btn-success mr-2" href="{{ url_for('auth.login')}}">Login</a>
            <a class="btn btn-lg btn-success" href="{{ url_for('auth.register')}}">Register</a>
        {% endif %}
    </p>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <h4>Definicija stanica</h4>
            <p>Aplikacija podržava definiciju stanica. Svaka stanica sadrži spasioce, i ima svog voditelja.</p>

            <h4>Definicija sposobnosti</h4>
            <p>Svaki spasioc može biti osposobljen za neku vrstu rada.</p>

            <h4>Akcije</h4>
            <p>112 Dispatcher može stvoriti akciju i pozvati spasioce da u njoj prisustvuju.</p>

            <h4>Definicija zadataka</h4>
            <p>U trenutnoj aktivnoj akciji 112 Dispatcher može davati direktne upute spasiocima preko karte.</p>

            <h4>Prikaz karte</h4>
            <p>Koristi se OpenStreetMap servis za detaljan prikaz karte. Na njoj se mogu ostavljati komentari, zadavati rute do neke točke i prikazati spasioce.</p>
        </div>

        <div class="col-lg-6">

            <h4>Izračun ruta</h4>
            <p>Aplikacija koristi OSRM servis za precizan izračun ruta. Spasioci mogu vidjeti točan put prema svom zadatku.</p>
            <div class="jumbotron" style="background-image: url(static/route.png); background-size: 100%; padding-top: 50%; background-repeat: no-repeat; width: 93%;"></div>

        </div>
    </div>

    <footer class="footer">
    <p>© samopython 2022</p>
    </footer>

</div>

{% endblock %}

src/templates/LoginForm.html.j2
{% extends "base.html" %}


{% block content %}
    {{ super() }}
    {{ form.csrf_token }}
    <div class="container-fluid">
      <div class="row h-75" style="margin-top:20vh">
        <div class="col-md-4 col-sm-4 col-xs-12">
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12 border rounded shadow">
            <form method="POST">
              <div class="mb-3 pt-2">
                {{ form.username.label(class="form-label")}}
                {{ form.username(class="form-control")}}
              <div class="mb-3">
                {{ form.password.label(class="form-label")}}
                {{ form.password(class="form-control")}}
              </div>
              <div class="mb-3 form-check"></div>
              {{ form.submit(class="btn btn-primary btn-block") }}
              <div class="form-text text-center text-danger">
                    {% if error %}
                        {{ error }}
                    {% endif %}
                </div>
            </form>
        </div>
        <div class="col-md-4 col-sm4 col-xs-12">
        <div class="row"></div>
{% endblock %}

src/templates/RegisterForm.html.j2
{% extends "base.html" %}

{% block content %}
{{ super() }}
<div class="row h-75" style="margin-top:3vh">
<div class="col-md-4 col-sm-4 col-xs-12 ml-2"></div>
<div class="border rounded shadow w-25">
<form method="POST" enctype = "multipart/form-data">
{{ form.csrf_token }}
  <div class="row">
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3">
            {{ form.name.label(class="form-label")}}
            {{ form.name(class="form-control") }}
        </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3">
            {{ form.surname.label(class="form-label")}}
            {{ form.surname(class="form-control") }}
        </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3">
                {{ form.username.label(class="form-label")}}
                {{ form.username(class="form-control") }}
        </div>
    </div>
    {% if error %}
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3 pt-4 text-center text-danger">
                {% for error in form.username.errors %}
                        {{ error }}
                {% endfor %}
        </div>
    </div>
    {% endif %}
  </div>
  <div class="row">
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3">
                {{ form.email.label(class="form-label") }}
                {{ form.email(class="form-control") }}
        </div>
    </div>
    {% if error %}
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3 pt-4 text-center text-danger">
                {% for error in form.email.errors %}
                        {{ error }}
                {% endfor %}
        </div>
    </div>
    {% endif %}
  </div>
  <div class="row">
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3 input-group">
                {{ form.phoneNumber.label(class="input-group-text") }}
                {{ form.phoneNumber(class="form-control mr-3") }}
        </div>
    </div>
    {% if error %}
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3 pt-4 text-center text-danger">
                {% for error in form.phoneNumber.errors %}
                        {{ error }}
                {% endfor %}
        </div>
    </div>
    {% endif %}
  </div>
  <div class="row">
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3">
                {{ form.password.label(class="form-label")}}
                {{ form.password(class="form-control") }}
        </div>
    </div>
    {% if error %}
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3 pt-4 text-center text-danger">
                {% for error in form.password.errors %}
                        {{ error }}
                {% endfor %}
        </div>
    </div>
    {% endif %}
  </div>
  <div class="row">
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3 ">
                {{ form.passwordCheck.label(class="form-label")}}
                {{ form.passwordCheck(class="form-control") }}
        </div>
    </div>
    {% if error %}
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3 pt-4 text-center text-danger">
                {% for error in form.passwordCheck.errors %}
                        {{ error }}
                {% endfor %}
        </div>
    </div>
    {% endif %}
  </div>
  <div class="row">
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3 input-group">
                {{ form.role.label(class="input-group-text") }}
                {{ form.role(class="form-select") }}
        </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3">
                {{ form.picture.label()}}
                {{ form.picture(class="form-control-file") }}
        </div>
    </div>
    {% if error %}
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3 pt-4">
                {% for error in form.picture.errors %}
                        {{ error }}
                {% endfor %}
        </div>
    </div>
    {% endif %}
  </div>
  <div class="row">
    <div class="col-md-11 col-sm-4 col-xs-12 ml-2">
        <div class="mb-3 mt-2 ml-3">
                {{ form.submit(class="btn btn-primary btn-block") }}
        </div>
    </div>
</form>
</div>
</div>
{% endblock %}

src/templates/RegisteredUsers.html.j2
{% extends "base.html" %}

{% block content %}
    {{ super() }}
    <table class="table">
        <thead>
            <tr>
            {% for col in ['ID', 'Username', 'First name', 'Last name', 'Tel', 'Email', 'Role', 'View'] %}
                <th scope="col">{{col}}</th>
            {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{user.id}}</td>
                    <td>{{user.korisnickoIme}}</td>
                    <td>{{user.ime}}</td>
                    <td>{{user.prezime}}</td>
                    <td>{{user.brojMob}}</td>
                    <td>{{user.email}}</td>
                    <td>{{user.uloga}}</td>
                    <td>
                        <button type="button" class="btn btn-primary" onclick="location.href='/user/view/{{user.id}}';">View</button>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% with messages = get_flashed_messages(with_categories=true)%}
    {% if messages %}
      {% for category, message in messages %}
      {% if category =="error" %}
        <div class="alert alert-danger alert-dismissable" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% else %}
        <div class="alert alert-success alert-dismissable" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}

    
{% endblock %}

src/templates/SetAbilityForm.hml.j2
{% extends "base.html" %}

{% block content %}
{{ super() }}
<div class="d-flex justify-content-center">
    <div class="h-75 w-25" style="margin-top:25vh">
        <div class="pt-3 col-md-10 col-sm-8 col-xs-12 border rounded shadow">
            <h4>Set new ability</h4>
            <form method="POST" enctype = "multipart/form-data" class="m-3">
                {{ form.csrf_token }}
                <div class="row pt-3">
                    {{ form.AbilityName.label()}}
                    {{ form.AbilityName(class="form-control selectpicker")}}
                </div>
                <div class="col-md-11 col-sm-4 col-xs-12 p-0 pt-4">
                    {{ form.submit(class="btn btn-primary w-100 ml-2") }}
                </div>
                <div class="form-text text-center text-danger">
                    {% if error %}
                        {{ error }}
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

src/templates/UserApplications.html.j2
{% extends "base.html" %}

{% block content %}
    {{ super() }}
    <table class="table">
        <thead>
            <tr>
            {% for col in ['Username', 'First name', 'Last name', 'Tel', 'Email', 'Role', 'Accept/Reject'] %}
                <th scope="col">{{col}}</th>
            {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{user.korisnickoIme}}</td>
                    <td>{{user.ime}}</td>
                    <td>{{user.prezime}}</td>
                    <td>{{user.brojMob}}</td>
                    <td>{{user.email}}</td>
                    <td>{{user.uloga}}</td>
                    <td style="display:flex">
                    <form action="{{url_for('applications.handle_application')}}" method="POST">
                        <button type="submit" class="btn btn-success mr-1" name="accept" value="{{user.korisnickoIme}}">Accept</button>
                    </form>
                    <form action="{{url_for('applications.handle_application')}}" method="POST">
                        <button type="submit" class="btn btn-danger" name="reject" value="{{user.korisnickoIme}}">Reject</button>
                    </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/templates/UserEditForm.html
{% extends "base.html" %}

{% block content %}
{{ super() }}

<div class="container fluid">
    <div class="h-75 w-75" style="margin-top: 3vh;">
        <div class="col-md-10 col-sm-8 col-xs-12 border rounded shadow">
            <h2>Change user data</h2>
            <form method="POST" enctype = "multipart/form-data">
                {{ form.csrf_token }}        
                    <div class="row">
                        {{ form.korisnickoIme.label(class="form-label col-3")}} <br>
                        {{ form.korisnickoIme(disabled = is_not_admin, class="flow-control col-8") }} 
                    </div>
                    <br>
                    <div class="row">
                        {{ form.ime.label(class="form-label col-3") }} <br>
                        {{ form.ime(disabled = is_not_admin, class="flow-control col-8") }} <br>
                    </div>
                    <br>
                    <div class="row">
                        {{ form.prezime.label(class="form-label col-3")}} <br>
                        {{ form.prezime(disabled = is_not_admin, class="flow-control col-8") }}
                    </div>
                    <br>
                    <div class="row ">
                        {{ form.brojMob.label(class="form-label col-3") }} <br>
                        {{ form.brojMob(disabled = is_not_admin, class="flow-control col-8") }}
                        {% for error in form.brojMob.errors %}
                        {{error}}
                        {% endfor %}<br>
                    </div>
                    <br>
                    <div class="row ">
                        {{ form.email.label(class="form-label col-3") }} <br>
                        {{ form.email(disabled = is_not_admin, class="flow-control col-8") }}
                        {% for error in form.email.errors %}
                        {{error}}
                        {% endfor %}<br>
                    </div>
                    <br>
                    <div class="row ">
                        {{ form.uloga.label(class="form-label col-3")}} <br>
                        {{ form.uloga(disabled = is_not_admin, class="flow-control col-4") }}<br>
                    </div>
                    <br>
                    <div class="row ">
                        {{ form.fotografija.label(class="form-label col-3") }} <br>
                        {{ form.fotografija(disabled = is_not_admin, class="flow-control col-8") }} <br>
                    </div>
                    <br>
                    <div class="row ">
                        {{ form.stanica.label(class="form-label col-3") }} <br>
                        {{ form.stanica(disabled = is_not_admin, class="flow-control col-4") }}
                    </div>
                    <br>
                    <div class="row ">
                        {{ form.lozinka.label(class="form-label col-3") }} <br>
                        {{ form.lozinka(disabled = is_not_admin, class="flow-control col-8") }} <br>
                    </div>
                    <br>
                    <div class="row">

                        {{ form.lozinkaProvjera.label(class="form-label col-3") }} <br>
                        {{ form.lozinkaProvjera(disabled = is_not_admin, class="flow-control col-8") }}
                    </div>
                    <br>
                    <div class="form-group ">
                        {{ form.submit(disabled = is_not_admin, class="flow-control btn btn-primary") }}
                    </div>
            </form>
        </div>
    </div>
</div>


{% endblock %}

src/templates/dodanKomentar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Comment added!</p>
<p>Changes will be seen after refreshing the page.</p>
</body>
</html>

src/templates/dodanZadatak.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>New task added!</p>
    <p>Changes will be seen after refreshing the page.</p>
</body>
</html>

src/templates/komentar.html.j2
{% block styles %}
            {{ bootstrap.load_css() }}
{% endblock %}

<div class="container-fluid">
      <div class="row h-100">
        <div class="col-md-4 col-sm-4 col-xs-12">
        </div>
        <div class="col-md-4 col-sm-4 col-xs-12 border rounded shadow">
            <form method="POST">
              <div class="mb-3 pt-2">
                {{ form.komentar.label(class="form-label")}}
                {{ form.komentar(class="form-control")}}
              </div>
              <div class="mb-3 form-check"></div>
              {{ form.submit(class="btn btn-success", value="Spremi") }}
                <button type="button" class="btn btn-primary"
                        onclick="location.href='/kartaAkcije/{{idAkcije}}/dodajNoviZadatak/{{ lat }}/{{ lon }}';">Dodaj novi zadatak</button>

              <div class="form-text text-center text-danger">
                    {% if error %}
                        {{ error }}
                    {% endif %}
                </div>
            </form>
            <div class="mb-3 pt-2">

            </div>
        </div>

        <div class="col-md-4 col-sm4 col-xs-12">
        <div class="row"></div>